### ISSUE TITLE
typo in code?

### ISSUE THREAD

**Issue by zippeurfou** [Planeshifter/text-miner#3]
Hi,
line 97, `self.dtm[d2] = self.dtm[d2].splice(w, 0.1);`
Shouldn't it be `self.dtm[d2] = self.dtm[d2].splice(w, 1);` ?
Best,

**Comment by Planeshifter** [comment]
Hi, 
thanks for the catch, the function was indeed not working properly. I have rewritten it and pushed a new version of the package to npm. Hope everything is now working as expected. Best,
Philipp
