### ISSUE TITLE
Stopwords key issue

### ISSUE THREAD

**Issue by cmuto09** [Planeshifter/text-miner#4]
Hey man, just a quick heads up on v0.2.x there is a object structure issue on STOPWORDS. Looks like it is meant to be structured like this:

`tm = {
    STOPWORDS: {
        EN: ...,
        ES: ...,
    }
}`

But it is actually structured like this:

`tm = {
    STOPWORDS:{
        STOPWORDS:{
            EN: ...
        }
    }
}`

Not a huge issue, but figured you'd want a heads up so you can edit the documentation

**Comment by Planeshifter** [comment]
Thanks for filing this issue! I did a major version bump and published a new version of the package (1.0.0)  which exports the stopwords as intended, so the package now will export

```
tm = { STOPWORDS: { EN: ..., ES: ..., } }
```
