### ISSUE TITLE
Text Miner returns "empty" vocabulary item instead of first stopword

### ISSUE THREAD

**Issue by bnvk** [Planeshifter/text-miner#6]
I've tested this a few times with different stopwords and configurations and can get repeated result.

```
var corpus = new TextMiner.Corpus([])

corpus.addDoc("wat cash money you go to boots and cats and dogs with me")
corpus.removeWords(TextMiner.STOPWORDS.EN)

var terms = new TextMiner.Terms(corpus)

=> [ 'wat', 'cash', 'money', '', 'boots', 'cats', 'dogs' ]
```

But if I move the first English stopword `you` two words left the "blank" word shifts two spaces left

```
corpus.addDoc("wat you cash money go to boots and cats and dogs with me")

=> [ 'wat', '', 'cash', 'money', 'boots', 'cats', 'dogs' ]
```

**Comment by Planeshifter** [comment]
After removing stop words, I added as step in which any extra whitespace is removed. So now both of your examples return the following:

```
=> [ 'wat', 'cash', 'money', 'boots', 'cats', 'dogs' ]
```

I pushed a new version of the package to `npm`.
