### ISSUE TITLE
terms.dtm returns doc cols as rows and keyword rows as cols

### ISSUE THREAD

**Issue by gitTerebi** [Planeshifter/text-miner#7]
Looks like it returns the array swapped on the axis.

If I try and pass the tdm into numeric.svd() - http://www.numericjs.com/documentation.html
It complains that the # of rows is less than # of cols.

I had to do an array transpose to fix it.

Your desc in help file suggests that it is doc on col, words on rows.

**Comment by Planeshifter** [comment]
Thanks! Sorry for that mistake in the documentation, it has been fixed by now.
